# Docker Compose configuration for development environment

services:
  web:
    extends:
      file: compose.service.yaml
      service: backend
    build:
      target: dev
    image: jcgroups-backend-dev
    ports:
      - "5050:5050"
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /code
          include:
            - configs/server.config.toml
        - action: rebuild
          path: pyproject.toml
        - action: rebuild
          path: uv.lock
        - action: rebuild
          path: Dockerfile
    volumes:
      - type: bind
        source: ${LOCAL_WORKSPACE_FOLDER}/src/
        target: /code/src
      - /code/src/app
    networks:
      - default

  worker:
    extends:
      file: compose.service.yaml
      service: backend
    build:
      target: dev
    image: jcgroups-backend-dev
    container_name: worker
    command: celery -A server.celery_app worker
    depends_on:
      - redis
      - rabbitmq
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /code
          include:
            - src/server
            - certs
            - configs/server.config.toml
        - action: rebuild
          path: pyproject.toml
        - action: rebuild
          path: uv.lock
        - action: rebuild
          path: Dockerfile
    networks:
      - default

  app:
    extends:
      file: compose.service.yaml
      service: frontend
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: .
          target: /code
          include:
            - src/app
            - public
            - configs/app.config.ts
            - nuxt.config.ts
            - tsconfig.json
            - pnpm-workspace.yaml
        - action: rebuild
          path: package.json
        - action: rebuild
          path: pnpm-lock.yaml
        - action: rebuild
          path: Dockerfile.vite
    volumes:
      - type: bind
        source: ${LOCAL_WORKSPACE_FOLDER}/.nuxt
        target: /code/.nuxt
    networks:
      - default

  nginx:
    extends:
      file: compose.service.yaml
      service: nginx
    build:
      target: dev
    image: jc-groups-manager-nginx-dev
    depends_on:
      - web
      - app
    networks:
      - default

  postgres:
    extends:
      file: compose.service.yaml
      service: postgres
    networks:
      - default

  redis:
    extends:
      file: compose.service.yaml
      service: redis
    ports:
      - "6379:6379"
    networks:
      - default

  rabbitmq:
    extends:
      file: compose.service.yaml
      service: rabbitmq
    networks:
      - default

volumes:
  pgdata:

networks:
  default:
    external: true
    name: jairocloud-groups-manager_default
