# syntax=docker/dockerfile:1

ARG OS_VERSION=trixie
ARG NODE_VERSION=26
ARG PNPM_VERSION=12

# ==============================
# Base stage: common setup
# ==============================
FROM docker.io/node:${NODE_VERSION}-${OS_VERSION} AS base

ARG PNPM_VERSION

WORKDIR /code
RUN chown node:node /code
RUN \
    --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt-get update && apt-get upgrade --yes \
    && \
    # Install system dependencies
    apt-get install --yes --no-install-recommends \
        python3 \
        make \
        g++
RUN npm install -g pnpm@${PNPM_VERSION} --allow-scripts=pnpm

USER node


# ==============================
# Development stage:
#   install dev dependencies and start dev server
# ==============================
FROM base AS dev

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN pnpm i --frozen-lockfile

COPY --chown=node:node . .

ENV NODE_ENV=development
ENV NUXT_PORT=3000

EXPOSE 3000
CMD [ "pnpm", "dev" ]
